name: note_app
description: "A Note app project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.2
  intl: ^0.19.0
  build_runner: ">=2.3.0 <4.0.0"
  retrofit: ">=4.0.0 <5.0.0"
  logger: any
  json_annotation: ^4.8.1
  sqflite:
  path:
  get_it: ^7.7.0
  equatable: ^2.0.0
  flutter_bloc: ^8.1.5
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter:
  uses-material-design: true
